### ISSUE TITLE
installing openlens via chocolatey does not work

### ISSUE THREAD

**Issue by mortenn** [virtualex-itv/chocolatey-packages#11]
Trying to install openlens using choco, it just launches the IDE from the temp directory
after closing openlens, it is not installed.

**Comment by virtualex-itv** [comment]
thank you for this, i've fixed my update script to resolve this but will have to manually push a new version.  The problem is I would have to append an extra digit to the current version number, and hope that a new version targetted as 6.5.3.xxx or even 6.5.4 or higher comes next, otherwise, i may have to un-list a few versions on the chocolatey repo.  in any case, a new package will be available soon.
