### ISSUE TITLE
vmwareworkstation 16.x: where can I place the installer so your package finds it?

### ISSUE THREAD

**Issue by schmonz** [virtualex-itv/chocolatey-packages#18]
Hi! Thank you for your packaging of VMware workstation.

I'm not reporting a bug or requesting a change, just asking for help. I hope my question is specific enough that you can promptly close this issue and not be too bothered that this is how I asked. :-)

I have a license for VMware 16.x, so I'm trying to `choco install` the final 16.x that you had packaged. This fails because the 16.x installer is no longer available from the expected vendor download URL.

I have a copy of the 16.x installer, though! So I'm hoping it's possible to place it exactly where the Chocolatey package would have downloaded it _to_, and then the package install could proceed as normal.

Is this possible? If so, what's the magic local filesystem location? (And as someone experienced with other package systems, how could I have figured this out myself?)

Thanks,

\- Amitai

**Comment by virtualex-itv** [comment]
Hi - unfortunately, it is not that simple.  The package already reads from it's manifest and then downloads the file from the appropriate URL.  In order to use a physical .exe file in the chocolatey installation, it would require that the script in the package itself be rewritten to call a local file instead of downloading it on-the-fly, and then would need to be repackaged for chocolatey or a local package.

The good news is that VMware Workstation 17.5.2 and later are now free for personal use, and only require a license if it is used commercially.

I've recently push the 17.5.2 package to the chocolatey repo, and will be pushing the 17.6.0 update shortly.

you can install it by running `choco install vmwareworkstation`
