### ISSUE TITLE
This is an unofficial distribution of Termius app

### ISSUE THREAD

**Issue by EvgeneOskin** [virtualex-itv/chocolatey-packages#3]
Hey @virtualex-itv,

Termius does not support chocolatey officially. The only official options to download the Termius app on windows is from [the website](https://termius.com/windows) or from [the windows store](https://www.microsoft.com/store/productId/9NK1GDVPX09V).

Could you please add a note that this package is not unofficial and official ones are on [the website](https://termius.com/windows) or from [the windows store](https://www.microsoft.com/store/productId/9NK1GDVPX09V)? Also, I request to change the package name from termius to termius-unofficial.

Cheers,
Eugene, Termius Team.

**Comment by virtualex-itv** [comment]
Hi @EvgeneOskin and thanks for reaching out!

First I'd like to start off by saying that I really like the Termius application and it's my "go-to" app on all windows installation for my SSH needs!  Awesome work!

While I understand your point, the URL used for this package to download and install the application is the same URL used when downloading from the website, this package just makes it less manually intensive and provides the ability to install it via the CLI using chocolatey rather than navigating the web or Microsoft store.  Thus, it's still an "official" Termius application completely untouched/unmodified.

If this is still of concern to you, I'm more than happy to add a comment on the package to reference the "official/supported" installation methods.  The only drawback though, is that unfortunately I cannot rename the package itself but can rename the visual "Title" of the package although I disagree with referring to this as "unofficial".  Renaming of a published chocolatey repo package is prohibited.

Again, I take no credit for the application, I am simply providing a quicker way to install the application from the official website leveraging a CLI utility for myself and the chocolatey community.

Let me know your thoughts!

Thx!

-virtualex-
